### ISSUE TITLE
Audio stutter or no audio on video start

### ISSUE THREAD

**Issue by katajakasa** [katajakasa/SDL_kitchensink#19]
For some videos, there is either no audio or audio stutters at video start. Find out why and fix.

**Comment by graphitemaster** [comment]
I think this may be the result of `av_rescale_rnd` for calculating the destination sample count in the packet handling for audio frames. `swr_convert` itself introduces a delay which can be calculated with `swr_get_delay(resampler, samplerate)`. This should be added to the sample count for the first argument of `av_rescale_rnd`.

**Comment by katajakasa** [comment]
Fixed in v1, https://github.com/katajakasa/SDL_kitchensink/tree/ttv-split-player

**Comment by ebachard** [comment]
Hi,

With another projects (miniDart), I'm using SDL2 + OpenGL + OpenCV + ImGui, and the sound was still missing. So I started to study what I could use, and my current search ended with SDL2 +  ffmpeg.

The first solution I found searching inside github, was SDL_ffmpeg, but is it not really maintained (looks like). Before I spent the day to replace deprecated ffmpeg functions / constants, I started replacing SDL with SDL2 when I was lucky to discover your repo :-)

**Thanks a lot for sharing your code, and for the fixes you did ! **

Back to the issue, I confirm the sound works better when using examplevideo + a video, using ttl-split-player branch.  What I did : I firstly merged the code + did the build on Linux 64 bits (x86_64), LinuxMint on an mbp6,2 (with Linux only installed), and I tested exampleaudio and examplevideo applications. The former works very well, and after a look in the issues list, I finaly tested the above mentioned branch.

If this can help you, the issue (crappy sound) still appears for : 
- big sized videos  (e.g. the famous bunny_1080p_60fps.mp4)
- or more than 30 fps frame rate

Other tests are ok, e.g. testing some youtube videos or equivalent (in terms of size / framerate).
Though, for me need (720p / 24 to 30 fps images), it is a very good start. Of course, if I can help you to improve, I'll propose PR.

I forgot : I tested both using with and without libass  ( USE_ASS = OFF), and since I do not need to use libass (I can draw whatever I need using ImGui), I definitely won't use it. Thanks again for the libass removing, who helps me a lot too :-)

HTH

**Comment by katajakasa** [comment]
Hey, the ttv-split-player branch will eventually become SDL_kitchensink v1. I dumped my latest codes, which introduces the ASS dependency again (though this time my intention is to make it completely optional).

The latest source in the branch is still heavily WIP, due to following things still needing work:
* Loading textures and subtitles via SDL_Surface (alternative to SDL_Texture)
* LibASS library dynamic loading (just like other SDL libraries do it)
* Seek improvements, currently this is unreliable
* Splitting decoders to their own threads (This should help with eg. 4K video)
* Better synchronization of decoder states, currently it's just dummy mutexes and timeouts. This needs proper blocking/waiting, eg. SDL_cond.
* Subtitle support is still very heavily WIP, current code is mostly for testing and toying.

**Comment by katajakasa** [comment]
Fixed in master.
